steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/schop-api:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/schop-api:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'schop-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/schop-api:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'PORT=8080,DB_HOST=34.56.16.173,DB_NAME=schopi-api,DB_USER=root,DB_PASSWORD=SchopiDB2024!'
    secretEnv: ['SERVICE_ACCOUNT_KEY']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/schop-api-key/versions/latest
      env: 'SERVICE_ACCOUNT_KEY'

images:
  - 'gcr.io/$PROJECT_ID/schop-api:$COMMIT_SHA'
