name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: schopi-sunucusu
  SERVICE: schopi-sunucusu
  REGION: us-west1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push
      run: |
        docker build -t "gcr.io/$PROJECT_ID/$SERVICE:latest" .
        docker push "gcr.io/$PROJECT_ID/$SERVICE:latest"

    - name: Deploy to Cloud Run
      if: "3" == "1" || "3" == "4"
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest
        flags: '--port=8080 --memory=512Mi --cpu=1'

    - name: Deploy to GKE
      if: "3" == "2"
      run: |
        gcloud container clusters get-credentials $SERVICE-cluster --region=$REGION
        kubectl set image deployment/$SERVICE $SERVICE=gcr.io/$PROJECT_ID/$SERVICE:latest
